# Generated by Django 5.1 on 2024-08-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_likedlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedlisting',
            name='like_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
